apiVersion: apps/v1
kind: Deployment
metadata:
  name: tssdata01
  labels:
    app: tssdata01
spec:
  selector:
    matchLabels:
      app: tssdata01
  replicas: 2
  template:
    metadata:
      labels:
        app: tssdata01
    spec:
      containers:
      - name: tssdata-web01
        image: alkarakully/tssdata-django:v1.1
        ports:
        - containerPort: 8000
