apiVersion: apps/v1
kind: Deployment
metadata:
  name: tssdata01
  labels:
    app: tssdata01
spec:
  selector:
    matchLabels:
      app: tssdata01
  replicas: 2
  template:
    metadata:
      labels:
        app: tssdata01
    spec:
      containers:
      - name: tssdata-web01
        image: alkarakully/nginx-tssdata
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
