apiVersion: v1
kind: Service
metadata:
  name: tssdata01
  namespace: default
  labels:
    app: tssdata01
spec:
  type: LoadBalancer
  selector:
    app: tssdata01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  loadBalancerIP: 

